name: '@namnh240795/verify-commit-message-action'
description: 'Verify pull request commit message'
inputs:
  github-token:
    description: 'Github token'
    required: true
outputs:
  pass: # id of output
    description: 'Verify commit message pass or not'
runs:
  using: 'node20'
  main: 'dist/index.js'